"""Shared fixtures and JAX setup for the sliced-committor test suite."""

import os

import jax

jax.config.update("jax_enable_x64", True)

import jax.numpy as jnp
import numpy as np
import pytest

GOLDEN_PATH = os.path.join(os.path.dirname(__file__), "golden", "beta_invariance_golden.npz")


@pytest.fixture(scope="session")
def golden_data():
    """Load the frozen reference snapshot generated by audit/verify_beta_invariance.py.

    The fixture exposes a dict-like object with the same keys the audit script saved:
    ``samples``, ``in_A``, ``in_B``, ``committors_1d``, ``directions``, all the
    weight dicts under ``w_diag::*`` / ``w_gram::*`` / ``w_bmc::*``,
    ``eps_equilibrium`` / ``eps_rms`` / ``eps_flux1d``, ``q_at_samples``,
    ``abc_v1::*``, ``abc_v2::*``, ``recal::*``. See the audit script for the full schema.
    """
    return np.load(GOLDEN_PATH, allow_pickle=False)


@pytest.fixture(scope="session")
def golden_samples(golden_data):
    return jnp.asarray(golden_data["samples"])


@pytest.fixture(scope="session")
def golden_labels(golden_data):
    return jnp.asarray(golden_data["in_A"]), jnp.asarray(golden_data["in_B"])
